### ISSUE TITLE
Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler

### ISSUE THREAD

**Issue by ferasallaou** [lukszar/QuickScanner#4]
I updated my XCode to Version 10.0 which brings Swift 4.2 as well. However, my QuickScanner Module is not working and I'm getting this error message

> Module compiled with Swift 4.1 cannot be imported by the Swift 4.2 compiler: /Users/Feras/Documents/P1/Carthage/Build/iOS/QuickScanner.framework/Modules/QuickScanner.swiftmodule/x86_64.swiftmodule

I tried to run Carthage update and I got this error message

> Build Failed
> 	Task failed with exit code 65:
> 	/usr/bin/xcrun xcodebuild -workspace /Users/Feras/Documents/P1/Carthage/Checkouts/QuickScanner/QuickScanner.xcworkspace -scheme QuickScanner -configuration Release -derivedDataPath /Users/Feras/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/QuickScanner/v0.7.7 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/09/2hwb_g256_11s0zcr38hqg200000gn/T/QuickScanner SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/Feras/Documents/P1/Carthage/Checkouts/QuickScanner)
> 
> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/09/2hwb_g256_11s0zcr38hqg200000gn/T/carthage-xcodebuild.XI2VQv.log

Is there anyway to update my Module to be compatible with Swift 4.2?

**Comment by lukszar** [comment]
Try meanwhile command: 
> carthage update --platform iOS --no-use-binaries

**Comment by ferasallaou** [comment]
Got the same issue unfortunately

**Comment by lukszar** [comment]
I will look on this ASAP and try to prepare new version for xcode 10.

**Comment by ferasallaou** [comment]
Thanks a lot 👍 Hope to hear from you soon

**Comment by lukszar** [comment]
@ferasallaou Let's try new version v0.8. Should work now.

**Comment by ferasallaou** [comment]
@lukszar Yup that Works :) Thanks a lot

**Comment by lukszar** [comment]
@ferasallaou perfect ;) If you like this framework, you can help to make it more popular by spreading the word or give a star :) Thanks for report a bug.
